/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js on the first `npm run dev` or `npm run build`.
// It is committed here so the project type-checks even before that first run.
